SELECT 
(SAMPLE(?e_label) AS ?root_net_name) (GROUP_CONCAT(?child_string ; SEPARATOR=" ") AS ?CHILDREN)
WHERE {
    # Hent ut all info om elnett, barn og data
    BIND(CONCAT("FACILITY: ", ?facility_name, " ", STR(?child_label)) AS ?child_string)
}
GROUP BY ?elnet
