SELECT
 (SAMPLE(?e_label) AS ?root_net_name) (GROUP_CONCAT(?child_label ; SEPARATOR=" ") AS ?CHILDREN)
WHERE {
    ?elnet a elnet:RootNetwork;
        rdfs:label ?e_label.
        #elnet:inFacility/rdfs:label ?anlegg.
    

    ?child elnet:hasParentNetwork* ?elnet.
    ?child rdfs:label ?child_label;
         elnet:inFacility ?facility.

}
GROUP BY ?elnet
