SELECT 
(SAMPLE(?anlegg) AS ?anlegg_navn) (SAMPLE(?e_label) AS ?root_net_name) (GROUP_CONCAT(?child_label ; SEPARATOR=" ") AS ?CHILDREN)
WHERE {
# Utvid root_networks til å også ta med alle barne-nettverk

}
GROUP BY ?elnet
